In [1]:
import numpy as np

---
##### numpy.datetime_as_string( arr , unit = None , timezone = 'naive' , casting = 'same_kind' ) 
    - Convertir una matriz de fechas de datos en una matriz de cadenas.

In [3]:
d = np.arange("2002-10-27T04:30", 4*60, 60, dtype="M8[m]")

In [4]:
d

array(['2002-10-27T04:30', '2002-10-27T05:30', '2002-10-27T06:30',
       '2002-10-27T07:30'], dtype='datetime64[m]')

* Establecer la zona horaria en UTC muestra la misma información, pero con un sufijo Z

In [5]:
np.datetime_as_string(d, timezone="UTC")

array(['2002-10-27T04:30Z', '2002-10-27T05:30Z', '2002-10-27T06:30Z',
       '2002-10-27T07:30Z'], dtype='<U35')

* Tenga en cuenta que elegimos tiempos de datos que cruzan un límite DST. Al pasar en un pytzobjeto de zona horaria se imprimirá el desplazamiento apropiado

In [7]:
np.datetime_as_string(d, timezone=pytz.timezone('US/Eastern'))

NameError: name 'pytz' is not defined

In [9]:
np.datetime_as_string(d, unit="h")

array(['2002-10-27T04', '2002-10-27T05', '2002-10-27T06', '2002-10-27T07'],
      dtype='<U32')

In [12]:
np.datetime_as_string(d, unit="s")

array(['2002-10-27T04:30:00', '2002-10-27T05:30:00',
       '2002-10-27T06:30:00', '2002-10-27T07:30:00'], dtype='<U38')

In [14]:
np.datetime_as_string(d, unit="h", casting="safe)

SyntaxError: EOL while scanning string literal (<ipython-input-14-8b8b86c5de9e>, line 1)

---
##### numpy.datetime_data( dtype , / ) 
    - Obtenga información sobre el tamaño de paso de un tipo de fecha u hora.


In [16]:
dt_25s=np.dtype("timedelta64[25s]")

In [18]:
np.datetime_data(dt_25s)

('s', 25)

In [20]:
np.array(10, dt_25s).astype("timedelta64[s]")

array(250, dtype='timedelta64[s]')

In [21]:
np.datetime64("2010", np.datetime_data(dt_25s))

numpy.datetime64('2010-01-01T00:00:00','25s')

---
##### class numpy.busdaycalendar( weekmask = '1111100' , holidays = None ) [fuente]
- Un objeto de calendario de días hábiles que almacena de manera eficiente la información que define los días válidos para la familia de funciones de días hábiles.

- Los días válidos predeterminados son de lunes a viernes ("días hábiles"). Se puede especificar un objeto busdaycalendar con cualquier conjunto de días semanales válidos, más las fechas opcionales de "vacaciones" que siempre serán inválidas.

- Una vez que se crea un objeto busdaycalendar, la máscara de semana y los días festivos no se pueden modificar.

In [22]:
bdd=np.busdaycalendar(holidays=["2011-07-01", "2011-07-04", "2011-07-17"])

In [23]:
bdd.weekmask

array([ True,  True,  True,  True,  True, False, False])

In [24]:
bdd.holidays

array(['2011-07-01', '2011-07-04'], dtype='datetime64[D]')

---
##### numpy.is_busday(dates, weekmask='1111100', holidays=None, busdaycal=None ,out=None ) 
* Calcula cuáles de las fechas indicadas son días válidos y cuáles no.

In [25]:
np.is_busday(["2011-07-01", "2011-07-02", "2011-07-18"], 
             holidays=["2011-07-01", "2011-07-04", "2011-07-17"])

array([False, False,  True])

In [53]:
np.is_busday(["2019-03-11", "2019-03-16", "2019-03-18"], 
             holidays=["2019-03-12", "2019-03-13", "2019-03-14"])

array([ True, False,  True])

---
##### numpy.busday_offset(fechas, desplazamientos, roll='raise', weekmask='1111100',holidays=None, busdaycal=None, out=None ) 
* Primero ajusta la fecha para que caiga en un día válido de acuerdo con la roll regla, luego aplica las compensaciones a las fechas dadas contadas en días válidos.

In [26]:
np.busday_offset("2011-10", 0, roll="forward") #Primer dia laboral de octubre

numpy.datetime64('2011-10-03')

In [28]:
np.busday_offset("2012-03", -1, roll="forward") # Ultimo dia laboral de febrero

numpy.datetime64('2012-02-29')

In [34]:
np.busday_offset("2011-01", 2, roll="forward", weekmask="Wed") # Third Wednesday in January 2011

numpy.datetime64('2011-01-19')

In [31]:
np.busday_offset("2012-05", 1, roll="forward", weekmask="Sun") # 2012 Mother's Day in Canada and the U.S.

numpy.datetime64('2012-05-13')

In [32]:
np.busday_offset("2011-03-20", 0, roll="forward") # First business day on or after a date

numpy.datetime64('2011-03-21')

In [35]:
np.busday_offset('2011-03-22', 0, roll='forward')

numpy.datetime64('2011-03-22')

In [37]:
np.busday_offset('2011-03-20', 1, roll='backward') # First business day after a date

numpy.datetime64('2011-03-21')

In [38]:
np.busday_offset('2011-03-22', 1, roll='backward')

numpy.datetime64('2011-03-23')

---
##### numpy.busday_count( begindates , enddates , weekmask = '1111100' , holidays = [] , busdaycal = None , out = None ) 
* Cuenta el número de días válidos entre comienzos y fechas finales , sin incluir el día de fechas finales .

In [47]:
np.busday_count('2019-03', '2019-04') # Number of weekdays in January 2011

21

In [46]:
 np.busday_count('2019', '2020') # Number of weekdays in 2011

261

In [45]:
np.busday_count('2019', '2020', weekmask='Sat') # Number of Saturdays in 2011

52