In [1]:
import numpy as np

---
#### numpy.c_= <numpy.lib.index_tricks.CClass object> 
* Traduce los objetos de división a concatenación a lo largo del segundo eje.

In [2]:
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [3]:
np.c_[np.array([[1,2,3]]), 0, 0, np.array([[4,5,6]])]

array([[1, 2, 3, 0, 0, 4, 5, 6]])

In [23]:
np.c_[np.array([[1,2,3]]),0,0, np.array([[1,2,3]])]

array([[1, 2, 3, 0, 0, 1, 2, 3]])

In [9]:
np.zeros((6,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

---
#### numpy.r_= <numpy.lib.index_tricks.RClass object> 
* Traduce los objetos de división a concatenación a lo largo del primer eje.

In [24]:
np.r_[np.array([1,2,3]), 0, 0, np.array([4,5,6])]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [25]:
np.r_[-1:1:6j, [0]*3, 5, 6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  0. ,  5. ,  6. ])

In [28]:
a = np.array([[0, 1, 2], [3, 4, 5]]) ; a

array([[0, 1, 2],
       [3, 4, 5]])

In [36]:
np.r_["-1", a, a] # concatenate along last axis

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [37]:
np.r_['0,2', [1,2,3], [4,5,6]] # concatenate along first axis, dim > = 2

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
np.r_['0,2,0', [1,2,3], [4,5,6]]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [39]:
np.r_['1,2,0', [1,2,3], [4,5,6]]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [40]:
np.r_['r',[1,2,3], [4,5,6]] #El uso de 'r' o 'c' como primer argumento de cadena crea una matriz.

matrix([[1, 2, 3, 4, 5, 6]])

---
#### numpy.s_= <numpy.lib.index_tricks.IndexExpression object> 
* Una mejor manera de construir tuplas de índice para matrices.

In [41]:
np.s_[2::2]

slice(2, None, 2)

In [42]:
np.index_exp[2::2]

(slice(2, None, 2),)

In [43]:
np.array((0,1,2,3,4))[np.s_[2::2]]

array([2, 4])