In [1]:
import numpy as np

---
#### numpy.reshape
* Da una nueva forma a una matriz sin cambiar sus datos.

In [2]:
a=np.arange(11,17).reshape((3,2))
a


array([[11, 12],
       [13, 14],
       [15, 16]])

In [3]:
np.reshape(a,(2,3))

array([[11, 12, 13],
       [14, 15, 16]])

In [4]:
a

array([[11, 12],
       [13, 14],
       [15, 16]])

In [5]:
b=np.reshape(a,(2,3))

In [6]:
b

array([[11, 12, 13],
       [14, 15, 16]])

In [7]:
c=np.reshape(np.ravel(b),(3,2))
c

array([[11, 12],
       [13, 14],
       [15, 16]])

In [8]:
c

array([[11, 12],
       [13, 14],
       [15, 16]])

In [9]:
type(c)

numpy.ndarray

In [10]:
a.shape

(3, 2)

In [11]:
b

array([[11, 12, 13],
       [14, 15, 16]])

In [12]:
a=np.zeros((10,2))

In [13]:
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
b=a.T
b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
c=b.view()

In [16]:
a=np.arange(6).reshape((3,2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [17]:
np.reshape(a, (2,3))

array([[0, 1, 2],
       [3, 4, 5]])

In [18]:
np.reshape(np.ravel(a), (2,3))

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
np.reshape(a, (2,3), order="F")

array([[0, 4, 3],
       [2, 1, 5]])

In [20]:
np.reshape(np.ravel(a, order="F"), (2,3))

array([[0, 2, 4],
       [1, 3, 5]])

In [21]:
np.reshape(np.ravel(a, order="F"), (3,2))

array([[0, 2],
       [4, 1],
       [3, 5]])

In [22]:
x=np.arange(11,17).reshape((3,2))

In [23]:
b=x.T

In [24]:
b

array([[11, 13, 15],
       [12, 14, 16]])

In [25]:
x

array([[11, 12],
       [13, 14],
       [15, 16]])

In [26]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
np.reshape(a,(6))

array([1, 2, 3, 4, 5, 6])

In [28]:
np.reshape(a, (6), order="F")

array([1, 4, 2, 5, 3, 6])

In [29]:
np.reshape(a, (3,-1))

array([[1, 2],
       [3, 4],
       [5, 6]])

---
#### numpy.ravel( a , orden = 'C' ) [fuente]
* Devuelve una matriz aplanada contigua.

In [30]:
x = np.array([[1,2,3], [4,5,6]])

In [31]:
print(np.ravel(x))

[1 2 3 4 5 6]


In [32]:
print(x.reshape(-1))
print(x.reshape(6))

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [33]:
np.ravel(x.T, order="A")

array([1, 2, 3, 4, 5, 6])

In [34]:
a=np.arange(3)[: : -1]; a

array([2, 1, 0])

In [35]:
a.ravel(order="C"); a

array([2, 1, 0])

In [36]:
a.ravel(order="K"); a

array([2, 1, 0])

In [37]:
a=np.arange(12).reshape(2,6);a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [38]:
a=np.arange(12).reshape(4,3);a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [39]:
a=np.arange(12).reshape(4,3);a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [40]:
a=np.arange(12).reshape(1,6,2).swapaxes(1,2);a

array([[[ 0,  2,  4,  6,  8, 10],
        [ 1,  3,  5,  7,  9, 11]]])

In [41]:
a=np.arange(12).reshape(2,3,2).swapaxes(2,1);a

array([[[ 0,  2,  4],
        [ 1,  3,  5]],

       [[ 6,  8, 10],
        [ 7,  9, 11]]])

In [42]:
a.ravel()

array([ 0,  2,  4,  1,  3,  5,  6,  8, 10,  7,  9, 11])

In [43]:
a.ravel(order="C")

array([ 0,  2,  4,  1,  3,  5,  6,  8, 10,  7,  9, 11])

In [44]:
a.ravel(order="K")

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### numpy.ndarray.flat 
* atributo

### ndarray.flat
* Un iterador 1-D sobre la matriz.

* Esta es una instancia numpy.flatiter , que actúa de manera similar a, pero no es una subclase de, el objeto iterador incorporado de Python.

In [45]:
x = np.arange(1,7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
x.flat[3]

4

In [47]:
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [48]:
x.T.flat[3]

5

In [49]:
type(x.flat)

numpy.flatiter

##### Un ejemplo de asignación

In [50]:
x.flat=3
x

array([[3, 3, 3],
       [3, 3, 3]])

In [51]:
x.flat[[1,4]] = 1
x

array([[3, 1, 3],
       [3, 1, 3]])

### numpy.ndarray.flatten 
* método

#### ndarray.flatten( orden = 'C' ) 
* Devuelve una copia de la matriz contraída en una dimensión.

In [52]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [53]:
a.flatten()

array([1, 2, 3, 4])

In [54]:
a.flatten("F")

array([1, 3, 2, 4])