In [5]:
import numpy as np

#### numpy.moveaxis( a , fuente , destino )
* Mueve los ejes de una matriz a nuevas posiciones.
* Otros ejes permanecen en su orden original.

In [6]:
x

NameError: name 'x' is not defined

In [7]:
np.moveaxis(x, -1, 0)

NameError: name 'x' is not defined

In [8]:
b=np.ravel(x)

NameError: name 'x' is not defined

In [9]:
b

NameError: name 'b' is not defined

In [10]:
np.moveaxis(b, -1,0)

NameError: name 'b' is not defined

In [11]:
np.moveaxis(b, 0,-1)

NameError: name 'b' is not defined

In [12]:
i=np.zeros((3,4,5))

In [13]:
np.moveaxis(i, 0,-2).shape

(4, 3, 5)

In [14]:
np.shape(i)

(3, 4, 5)

In [15]:
np.transpose(i).shape

(5, 4, 3)

In [16]:
np.swapaxes(i, 0, -1).shape

(5, 4, 3)

In [17]:
np.moveaxis(i, [0,1], [-1,-2]).shape

(5, 4, 3)

In [18]:
np.moveaxis(i, [0,1,2],[-1,-2,-3]).shape

(5, 4, 3)

#### numpy.rollaxis( a , eje , inicio = 0 )

* Cambia el eje especificado hacia una posición determinada.
* Esta función sigue siendo compatible con versiones anteriores, pero debería preferir la moveaxis. La función moveaxis fue agregada en NumPy 1.11.



In [19]:
x = np.ones((3,4,5,6))

In [20]:
np.rollaxis(x, 3,1).shape

(3, 6, 4, 5)

In [21]:
np.rollaxis(x, 0, 3).shape

(4, 5, 3, 6)

In [22]:
np.shape(x)

(3, 4, 5, 6)

In [23]:
np.rollaxis(x, 1, 0).shape

(4, 3, 5, 6)

In [24]:
b=np.rollaxis(x, 3,0).shape

In [25]:
b

(6, 3, 4, 5)

#### numpy.swapaxes( a , axis1 , axis2 )
* Intercambia dos ejes de una matriz.

In [26]:
x = np.array([[3,5,6]])
x

array([[3, 5, 6]])

In [27]:
np.swapaxes(x, 0, 1)

array([[3],
       [5],
       [6]])

In [28]:
i = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
i

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [29]:
np.swapaxes(i, 0,1)

array([[[0, 1],
        [4, 5]],

       [[2, 3],
        [6, 7]]])

In [30]:
np.swapaxes(i, 2, 0)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [31]:
np.swapaxes(i, 1, 0)

array([[[0, 1],
        [4, 5]],

       [[2, 3],
        [6, 7]]])

In [32]:
i[0][0][0], i[0][0][1], i[0][1][0], i[0][1][1], i[1][0][0], i[1][0][1], i[1][1][0], i[1][1][1]

(0, 1, 2, 3, 4, 5, 6, 7)

#### numpy.ndarray.T 

* atributo

### ndarray.T

* Igual que self.transpose (), excepto que self se devuelve si self.ndim <2.



In [33]:
x = np.array([[1. , 2.], [3.,4.]])

In [34]:
x

array([[1., 2.],
       [3., 4.]])

In [35]:
x.T

array([[1., 3.],
       [2., 4.]])

In [36]:
x = np.array([1.,2,3,4])

In [37]:
x

array([1., 2., 3., 4.])

In [38]:
x.T

array([1., 2., 3., 4.])

#### numpy.transpose( a , ejes = Ninguno )

* Permuta las dimensiones de una matriz.

In [39]:
x = np.arange(6).reshape((3,2))

In [40]:
x.shape

(3, 2)

In [41]:
np.transpose(x).shape

(2, 3)

In [42]:
i = np.ones((1,2,3,4))

In [43]:
i.shape

(1, 2, 3, 4)

In [44]:
i.transpose().shape

(4, 3, 2, 1)

In [45]:
np.transpose(i, (3,2,0,1)).shape

(4, 3, 1, 2)