In [1]:
import numpy as np


#### numpy.atleast_1d 
### numpy.atleast_1d( * arys )

* Convertir entradas a matrices con al menos una dimensión.

* Las entradas escalares se convierten en matrices unidimensionales, mientras que las entradas de dimensiones superiores se conservan.

In [2]:
x = np.arange(9.).reshape(3,3)

In [3]:
x.shape

(3, 3)

In [4]:
x

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [5]:
np.atleast_1d(x)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [6]:
np.atleast_1d(x) is x

True

In [7]:
np.atleast_1d(1,2, [3,4], [5,6])

[array([1]), array([2]), array([3, 4]), array([5, 6])]

#### atleast_2d

In [8]:
np.atleast_2d(3.0)

array([[3.]])

In [9]:
j = np.arange(3.)

In [10]:
np.atleast_2d(j)

array([[0., 1., 2.]])

In [11]:
np.atleast_2d(j).base is j

True

In [12]:
np.atleast_2d(j).base

array([0., 1., 2.])

In [13]:
np.atleast_2d(1,[1,2],[1,2])

[array([[1]]), array([[1, 2]]), array([[1, 2]])]

#### atleast_3d

In [14]:
np.atleast_3d(3.)

array([[[3.]]])

In [15]:
k = np.arange(3.)

In [16]:
np.atleast_3d(k).shape

(1, 3, 1)

In [17]:
x = np.arange(12.).reshape(4,3)

In [18]:
np.atleast_3d(x).shape

(4, 3, 1)

In [19]:
np.atleast_3d(x).base is x.base

True

In [20]:
for arr in np.atleast_3d([1,2],[[1,2]], [[[1,2]]]):
    print(arr, arr.shape)

[[[1]
  [2]]] (1, 2, 1)
[[[1]
  [2]]] (1, 2, 1)
[[[1 2]]] (1, 1, 2)


### numpy.broadcast_to
#### numpy.broadcast_to( array , shape , subok = False )
* Transmitir una matriz a una nueva forma.

In [21]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [22]:
np.broadcast_to(x, (3,3))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

#### numpy.broadcast_arrays 
### numpy.broadcast_arrays( * args , ** kwargs ) [fuente]
* Transmitir cualquier número de matrices entre sí.

In [23]:
x = np.array([[1,2,3]])
x

array([[1, 2, 3]])

In [24]:
y = np.array([[4],[5]])
y

array([[4],
       [5]])

In [25]:
np.broadcast_arrays(x,y)

[array([[1, 2, 3],
        [1, 2, 3]]), array([[4, 4, 4],
        [5, 5, 5]])]

In [26]:
[np.array(a) for a in np.broadcast_arrays (x,y)]

[array([[1, 2, 3],
        [1, 2, 3]]), array([[4, 4, 4],
        [5, 5, 5]])]

#### numpy.expand_dims 
### numpy.expand_dims( a , eje )
* Expandir la forma de una matriz.

* Inserte un nuevo eje que aparecerá en la posición del eje en la forma de matriz expandida.

In [27]:
x = np.array([1,2])

In [28]:
x.shape

(2,)

In [29]:
y = np.expand_dims(x, axis=0)

In [30]:
y

array([[1, 2]])

In [31]:
y.shape

(1, 2)

In [32]:
y = np.expand_dims(x, axis=1)

In [33]:
y.shape

(2, 1)

In [34]:
np.newaxis is None

True

#### numpy.squeeze 
### numpy.squeeze( a , eje = Ninguno )
* Eliminar entradas unidimensionales de la forma de una matriz.

In [35]:
x = np.array([[[0], [1], [2] ]])

In [36]:
x.shape

(1, 3, 1)

In [37]:
np.squeeze(x).shape

(3,)

In [38]:
np.squeeze(x, axis=0).shape

(3, 1)

In [39]:
np.squeeze(x, axis=1).shape

ValueError: cannot select an axis to squeeze out which has size not equal to one

In [ ]:
np.squeeze(x, axis=2).shape

In [ ]:
x