In [1]:
import numpy as np

### numpy.asarray 
#### numpy.asarray (a , dtype = Ninguno , orden = Ninguno)
- Convertir la entrada a una matriz.

1. Convertir una lista en una matriz

In [2]:
a = [1,2]

In [3]:
a

[1, 2]

In [5]:
np.asarray(a)

array([1, 2])

In [7]:
i = ["Uno", "Dos", "Tres", "Cuatro"]
i

['Uno', 'Dos', 'Tres', 'Cuatro']

In [8]:
np.asarray(i)

array(['Uno', 'Dos', 'Tres', 'Cuatro'], dtype='<U6')

In [10]:
j=[[1,2],[3,4],[5,6]]
type(j)

list

In [14]:
jj = np.asarray(j)

In [17]:
type(jj)

numpy.ndarray

In [18]:
jj

array([[1, 2],
       [3, 4],
       [5, 6]])

2. las matrices existentes no se copian

In [27]:
b = np.array([1,2])
b

array([1, 2])

In [29]:
np.asarray(b) is b

True

3. Si dtype se establece, la matriz se copia solo si dtype no coincide:

In [30]:
c = np.array([1,2], dtype=np.float32)
c

array([1., 2.], dtype=float32)

In [32]:
np.asarray(c, dtype=np.float32) is c

True

In [33]:
np.asarray(c, dtype=np.float64) is c

False

4. Contrariamente a asanyarray, las subclases ndarray no se pasan a través de:

In [34]:
issubclass(np.recarray, np.ndarray)

True

In [37]:
a = np.array([(1.0,2),(3.0,4)], dtype="f4,i4").view(np.recarray)

In [39]:
a

array([1, 2])

In [40]:
np.asarray(a) is a

True

In [41]:
np.asanyarray(a) is a

True

### numpy.asanyarray 
#### numpy.asanyarray (a, dtype=Ninguno, orden=Ninguno)
* Convierte la entrada a un ndarray, pero pasa las subclases a través de ndarray.

1. Convertir una lista en una matriz:

In [42]:
a=[1,2]

In [43]:
np.asanyarray(a)

array([1, 2])

Las instancias de las subclases de ndarray  se pasan como:

In [44]:
a=np.array([(1.,2),(3,4)], dtype="f4,i4").view(np.recarray)

In [45]:
np.asanyarray(a) is a

True

### numpy.asmatrix 
#### numpy.asmatrix (data, dtype=None)

* Interpreta la entrada como una matriz.

* A diferencia matrix, asmatrix no hace una copia si la entrada ya es una matriz o un ndarray. Equivalente a .matrix(data, copy=False)

In [50]:
x = np.array([[10,20],[30,40]])

In [51]:
m=np.asmatrix(x)

In [52]:
x[0,0]=5

In [53]:
m

matrix([[ 5, 20],
        [30, 40]])

### numpy.asfarray 
#### numpy.asfarray (a, dtype=<class'numpy.float64'>)

- Devuelve una matriz convertida en un tipo flotante.

In [54]:
np.asfarray([2,3])

array([2., 3.])

In [55]:
np.asfarray([2,3], dtype="float")

array([2., 3.])

In [56]:
np.asfarray([2,3], dtype="int8")

array([2., 3.])

### numpy.asfortranarray 
#### numpy.asfortranarray( a , dtype = Ninguno )

- Devuelve una matriz (ndim> = 1) dispuesta en orden de Fortran en la memoria.

In [57]:
x = np.arange(6).reshape(2,3)

In [60]:
y = np.asfortranarray(x)

In [62]:
x.flags["F_CONTIGUOUS"]

False

In [63]:
y.flags["F_CONTIGUOUS"]

True

### numpy.ascontiguousarray 
#### numpy.ascontiguousarray( a , dtype = Ninguno ) [fuente]

- Devuelve una matriz contigua (ndim> = 1) en la memoria (orden C).

In [64]:
x = np.arange(6).reshape(2,3)

In [65]:
np.ascontiguousarray(x, dtype=np.float32)

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)

In [69]:
x.flags["C_CONTIGUOUS"]

True

### numpy.asarray_chkfinite 
#### numpy.asarray_chkfinite( a , dtype = Ninguno , orden = Ninguno ) [fuente]

- Convierta la entrada a una matriz, verificando si hay NaNs o Infs.

1. Convertir una lista en una matriz. Si todos los elementos son finitos asarray_chkfinitees idéntico a asarray.

In [71]:
a = [1,2]

In [72]:
np.asarray_chkfinite(a, dtype=float)

array([1., 2.])

Aumenta ValueError si array_like contiene Nans o Infs.

In [73]:
a = [1,2, np.inf]

In [74]:
try:
    np.asarray_chkfinite(a)
except ValueError:
    print("ValueError")
ValueError

ValueError


ValueError

### numpy.asscalar 
#### numpy.asscalar( a ) [fuente]

- Convertir una matriz de tamaño 1 a su equivalente escalar.

In [75]:
np.asscalar(np.array([24]))

24

In [78]:
i = np.asscalar(np.array([24]))

In [79]:
i

24

In [80]:
type(i)

int

### numpy.require 
#### numpy.require( a , dtype = Ninguno , requisitos = Ninguno ) [fuente]

- Devuelva un ndarray del tipo proporcionado que cumpla con los requisitos.

- Esta función es útil para asegurarse de que se devuelva una matriz con los indicadores correctos para pasar al código compilado (quizás a través de ctypes).

In [83]:
x = np.arange(6).reshape(2,3)
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [85]:
i = np.arange(12).reshape(4,3)

In [86]:
i

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [87]:
i.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [88]:
y = np.require(x, dtype=np.float32, requirements=["A", "O", "W", "F"])

In [89]:
y.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False