In [1]:
import numpy as np

* concatenate : Unir una secuencia de matrices a lo largo de un eje existente.
* stack(matrices) : Unir una secuencia de matrices a lo largo de un nuevo eje.
* column_stack : Apile matrices 1-D como columnas en una matriz 2-D.
* dstack : Apilar las matrices en secuencia de profundidad (a lo largo del tercer eje).
* hstack : Apilar matrices en secuencia horizontalmente (columna sabia).
* vstack : Apilar matrices en secuencia verticalmente (fila sabio).
* block(matrices) : Armar un nd-array a partir de listas anidadas de bloques.

### numpy.concatenate 
#### numpy.concatenate( (a1 , a2 , ...) , axis = 0 , out = None ) 

- Unir una secuencia de matrices a lo largo de un eje existente.

In [2]:
a = np.array([[1,2] , [3,4]])

In [3]:
b = np.array([[5,6]])

In [4]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [122]:
np.concatenate((a,b), axis=None)

array([2., 0., 0., 0., 2., 0., 0., 0., 2., 3., 0., 0., 0., 3., 0., 0., 0.,
       3.])

In [148]:
x = np.ones((2,1))
y = np.zeros((2,3))
np.concatenate((x,y), axis=1)

array([[1., 0., 0., 0.],
       [1., 0., 0., 0.]])

1. Esta función no conservará el enmascaramiento de las entradas MaskedArray.

In [156]:
a = np.arange(3) ; a

array([0, 1, 2])

In [160]:
a = np.ma.arange(3) ; a

masked_array(data=[0, 1, 2],
             mask=False,
       fill_value=999999)

In [161]:
a[1] = np.ma.masked

In [162]:
b = np.arange(2,5) ; b

array([2, 3, 4])

In [167]:
a

masked_array(data=[0, --, 2],
             mask=[False,  True, False],
       fill_value=999999)

In [164]:
b

array([2, 3, 4])

In [165]:
np.concatenate([a,b])

masked_array(data=[0, 1, 2, 2, 3, 4],
             mask=False,
       fill_value=999999)

In [166]:
np.ma.concatenate([a,b])

masked_array(data=[0, --, 2, 2, 3, 4],
             mask=[False,  True, False, False, False, False],
       fill_value=999999)

### numpy.stack 
#### numpy.stack( arrays , axis = 0 , out = None ) [fuente]

- Unir una secuencia de matrices a lo largo de un nuevo eje.

- El parámetro de eje especifica el índice del nuevo eje en las dimensiones del resultado. Por ejemplo, si axis=0 será la primera dimensión y si axis=-1 será la última dimensión.

In [218]:
arrays = [np.random.randn(3,4) for  _ in range(10)] ; arrays

[array([[-0.85543663, -0.74906676,  0.43636615, -2.21825927],
        [-0.22578287,  2.12420589,  0.19109187, -1.39129444],
        [ 0.40570961,  1.23912292, -0.14552353,  2.09492647]]),
 array([[-0.72965326, -0.03990624, -0.67561808,  0.01632265],
        [-0.37598494,  0.77439999,  0.13176053, -1.31556358],
        [-1.46641012,  0.62352434,  0.57377149,  1.06279246]]),
 array([[ 0.20672801,  0.23505525, -1.07779376, -1.31182015],
        [ 0.23150472, -0.1967677 , -1.25118317,  0.25921946],
        [-0.87478653, -1.93116832, -0.91394767, -0.00805654]]),
 array([[-2.15979473, -0.30914869,  0.25366192,  0.11007551],
        [-0.57086485, -1.03168726, -2.07182033, -0.49728403],
        [-0.74866155,  1.41494626, -0.58547082, -0.10867142]]),
 array([[ 0.36875954,  0.92111807, -1.03172224,  1.30446898],
        [-0.05510516, -0.78087971, -0.23306223, -0.75807188],
        [ 0.15465679, -1.45735557, -0.95665683, -1.28166045]]),
 array([[ 0.14481965, -1.8992195 , -0.33518502,  0.17607403]

In [222]:
np.stack(arrays, axis=2).shape

(3, 4, 10)

In [227]:
j = np.stack(arrays, axis=2) ; len(j)

3

In [211]:
i =np.stack(arrays, axis=1) ; i

array([[[-0.58989873,  0.47271066, -0.77488257,  0.75896488],
        [ 0.93914609, -0.30151489, -1.03367582,  1.56447589],
        [-1.02236488, -1.02436185,  0.17601328,  0.28780776],
        [-2.17069323,  0.07890601, -0.13678209,  0.18699706],
        [ 0.05504586, -0.61033956, -1.68732151,  1.08003825],
        [-0.92228462, -0.67840231,  0.64967523,  1.9495621 ],
        [ 1.4612021 , -0.12743722, -2.41260272,  1.76583196],
        [-2.13167285, -0.33959028, -0.4092303 ,  0.1783158 ],
        [-1.23677374,  0.78654773, -1.33680691,  0.24678458],
        [ 0.13619866, -1.14577865, -0.40028072,  0.74693637]],

       [[-0.1582412 ,  0.02218756,  0.08663916, -0.67273698],
        [-1.6134763 ,  0.08248065,  0.10652411, -0.56325623],
        [ 0.57307701,  0.75564961,  0.54166807, -0.24971505],
        [-1.43930017, -0.68980658, -0.01105212,  0.20275534],
        [ 0.25092062,  0.17774526, -1.61168736,  0.75046407],
        [-0.36594517,  1.21726707,  0.73838392,  0.69499625],
      

In [201]:
i[0][2][3]

0.5839419705240159

In [230]:
np.stack(arrays, axis=1).shape

(3, 10, 4)

In [231]:
np.stack(arrays, axis=2).shape

(3, 4, 10)

In [232]:
a = np.array([1,2,3])

In [233]:
b = np.array([2,3,4])

In [234]:
np.stack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [290]:
ii = np.zeros((3,2)) ; print(ii), print()
jj = np.ones((3,2)) ; print(jj), print("stack")
yy = np.stack((ii,jj), axis=2) ;  print(yy), print("Column stack")
zz = np.column_stack((ii,jj)) ; print(zz), print("dstack")
aa = np.dstack((ii,jj)) ; print(aa)

yy.shape

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]
stack
[[[0. 1.]
  [0. 1.]]

 [[0. 1.]
  [0. 1.]]

 [[0. 1.]
  [0. 1.]]]
Column stack
[[0. 0. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 1. 1.]]
dstack
[[[0. 1.]
  [0. 1.]]

 [[0. 1.]
  [0. 1.]]

 [[0. 1.]
  [0. 1.]]]


(3, 2, 2)

In [291]:
yy == aa

array([[[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

### numpy.column_stack 
#### numpy.column_stack( tup ) [fuente]

- Apila matrices 1-D como columnas en una matriz 2-D.

- Tome una secuencia de arreglos 1-D y los apila como columnas para hacer un solo arreglo 2-D. Las matrices 2-D se apilan como están, al igual que con hstack. Las matrices 1-D se convierten primero en columnas 2-D.

In [251]:
a = np.array((11,12,13))

In [252]:
b = np.array((22,23,24))

In [253]:
np.column_stack((a,b))

array([[11, 22],
       [12, 23],
       [13, 24]])

In [261]:
ii = np.zeros((3,2)) ; print(ii), print()
jj = np.ones((3,2)) ; print(jj), print()
yy = np.column_stack((ii,jj)) ; print(yy)

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]

[[0. 0. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 1. 1.]]


### numpy.dstack 
#### numpy.dstack( tup ) [fuente]

- Apila las matrices en secuencia de profundidad (a lo largo del tercer eje).

- Esto es equivalente a la concatenación a lo largo del tercer eje después de que las matrices de forma 2-D (M, N) se hayan reformado a (M, N, 1) y las matrices de forma 1-D (N,) se hayan reformado a (1, N, 1) . Reconstruye arrays divididos por dsplit.

- Esta función tiene más sentido para arreglos con hasta 3 dimensiones. Por ejemplo, para datos de píxeles con una altura (primer eje), ancho (segundo eje) y r / g / b canales (tercer eje). Las funciones concatenate, stacky block proporcionan operaciones más generales de apilamiento y concatenación.

In [24]:
a = np.array((11,22,33))

In [25]:
b = np.array((22,33,44))

In [26]:
np.dstack((a,b))

array([[[11, 22],
        [22, 33],
        [33, 44]]])

In [27]:
a = np.array(((1),(2),(3)))

In [28]:
b = np.array(((22),(33),(44)))

In [29]:
np.dstack((a,b))

array([[[ 1, 22],
        [ 2, 33],
        [ 3, 44]]])

### numpy.hstack 
#### numpy.hstack( tup ) [fuente]

- Apilar matrices en secuencia horizontalmente (columna sabia).

- Esto es equivalente a la concatenación a lo largo del segundo eje, a excepción de las matrices 1-D donde concatena a lo largo del primer eje. Reconstruye arrays divididos por hsplit.

- Esta función tiene más sentido para arreglos con hasta 3 dimensiones. Por ejemplo, para datos de píxeles con una altura (primer eje), ancho (segundo eje) y r / g / b canales (tercer eje). Las funciones concatenate, stacky blockproporcionan operaciones más generales de apilamiento y concatenación.

In [30]:
a = np.array((1,2,3))

In [31]:
b = np.array((22,33,44))

In [32]:
np.hstack((a,b))

array([ 1,  2,  3, 22, 33, 44])

In [33]:
a = np.array([[1],[2],[3]])

In [34]:
b = np.array([[22],[33],[44]])

In [35]:
np.hstack((a,b))

array([[ 1, 22],
       [ 2, 33],
       [ 3, 44]])

### numpy.vstack 
#### numpy.vstack( tup ) [fuente]

- Apilar matrices en secuencia verticalmente (fila sabio).

- Esto es equivalente a la concatenación a lo largo del primer eje después de que los arreglos 1-D de forma (N,) se hayan reformado a (1, N) . Reconstruye arrays divididos por vsplit.

- Esta función tiene más sentido para arreglos con hasta 3 dimensiones. Por ejemplo, para datos de píxeles con una altura (primer eje), ancho (segundo eje) y r / g / b canales (tercer eje). Las funciones concatenate, stacky blockproporcionan operaciones más generales de apilamiento y concatenación.

In [36]:
a = np.array([1,2,3])

In [37]:
b = np.array([22,33,44])

In [38]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [22, 33, 44]])

In [39]:
a = np.array([[1],[2],[3]])

In [40]:
b = np.array([[22],[33],[44]])

In [41]:
np.vstack((a,b))

array([[ 1],
       [ 2],
       [ 3],
       [22],
       [33],
       [44]])

### numpy.block 
#### numpy.block (matrices)

- Arma un nd-array a partir de listas anidadas de bloques.

- Los bloques en las listas más internas se concatenan (vea concatenate) a lo largo de la última dimensión (-1), luego se concatenan a lo largo de la segunda última dimensión (-2), y así sucesivamente hasta que se alcanza la lista más externa.

- Los bloques pueden ser de cualquier dimensión, pero no se emitirán utilizando las reglas normales. En su lugar, se insertan ejes delanteros de tamaño 1, para hacer block.ndim lo mismo para todos los bloques. Esto es principalmente útil para trabajar con escalares, y significa que el código como es válido, donde .np.block([v, 1])v.ndim == 1

- Cuando la lista anidada tiene dos niveles de profundidad, esto permite construir matrices de bloques a partir de sus componentes.

In [92]:
a = np.eye(3) * 2 ; a

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [87]:
a.shape, type(a), a.dtype

((2, 2), numpy.ndarray, dtype('float64'))

In [88]:
b = np.eye(3) * 3 ; b

array([[3., 0., 0.],
       [0., 3., 0.],
       [0., 0., 3.]])

In [89]:
b.shape, type(b), b.dtype

((3, 3), numpy.ndarray, dtype('float64'))

In [91]:
np.block([[a, np.zeros((2,3))], [np.ones((3,2)), b]])

array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [1., 1., 3., 0., 0.],
       [1., 1., 0., 3., 0.],
       [1., 1., 0., 0., 3.]])

In [104]:
i = np.ones((3,3)) ; i 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [110]:
j = np.ones((2,3)) ; j

array([[1., 1., 1.],
       [1., 1., 1.]])

In [111]:
y = np.block([[i, np.zeros((3,3))],[np.zeros((2,3)), j]]) ; y

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [112]:
ii = np.ones((2,2))

In [113]:
jj = np.ones((2,2))

In [117]:
yy = np.block([[ii, np.zeros((2,2))], [np.zeros((2,2)), jj]]) ; yy

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])