In [13]:
import numpy as np

### numpy.split 
#### numpy.split (ary , indices_or_sections, axis=0)

- Dividir una matriz en múltiples sub-matrices.

In [2]:
x = np.arange(9.) ; x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [3]:
np.split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [4]:
y = np.arange(8) ; y

array([0, 1, 2, 3, 4, 5, 6, 7])

In [5]:
np.split(y , [2,4,6,10])

[array([0, 1]),
 array([2, 3]),
 array([4, 5]),
 array([6, 7]),
 array([], dtype=int64)]

### numpy.array_split 
#### numpy.array_split(ary, indices_or_sections, axis=0)

- Dividir una matriz en múltiples sub-matrices.

- Refiérase a la documentación split. La única diferencia entre estas funciones es que array_split permite que indices_or_sections sea un entero que no divide por igual el eje. Para una matriz de longitud l que debe dividirse en n secciones, devuelve l% n subarreglas de tamaño l // n + 1 y el resto de tamaño l // n.

In [6]:
x = np.arange(8) ; x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [7]:
np.array_split(x, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7])]

In [8]:
y = np.zeros((4,4)) ; y

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.array_split(y, 2)

[array([[0., 0., 0., 0.],
        [0., 0., 0., 0.]]), array([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])]

In [10]:
z = np.array_split(y, 2) ; z

[array([[0., 0., 0., 0.],
        [0., 0., 0., 0.]]), array([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])]

In [11]:
z[0]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### numpy.dsplit 
#### numpy.dsplit(ary, indices_or_sections)

- Divida la matriz en múltiples subarreglos a lo largo del 3er eje (profundidad).

- dsplit es equivalente a split con axis=2, la matriz siempre se divide a lo largo del tercer eje siempre que la dimensión de la matriz sea mayor o igual a 3.

In [28]:
x = np.arange(36).reshape(2,3,6) ; x

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

In [34]:
np.dsplit(x, 3)

[array([[[ 0,  1],
         [ 6,  7],
         [12, 13]],
 
        [[18, 19],
         [24, 25],
         [30, 31]]]), array([[[ 2,  3],
         [ 8,  9],
         [14, 15]],
 
        [[20, 21],
         [26, 27],
         [32, 33]]]), array([[[ 4,  5],
         [10, 11],
         [16, 17]],
 
        [[22, 23],
         [28, 29],
         [34, 35]]])]

In [32]:
np.dsplit(x, np.array([2,4]))

[array([[[ 0,  1],
         [ 6,  7],
         [12, 13]],
 
        [[18, 19],
         [24, 25],
         [30, 31]]]), array([[[ 2,  3],
         [ 8,  9],
         [14, 15]],
 
        [[20, 21],
         [26, 27],
         [32, 33]]]), array([[[ 4,  5],
         [10, 11],
         [16, 17]],
 
        [[22, 23],
         [28, 29],
         [34, 35]]])]

In [37]:
y = np.arange(16.).reshape(2,2,4) ; y

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])

In [36]:
np.dsplit(y, np.array([3,6]))

[array([[[ 0.,  1.,  2.],
         [ 4.,  5.,  6.]],
 
        [[ 8.,  9., 10.],
         [12., 13., 14.]]]), array([[[ 3.],
         [ 7.]],
 
        [[11.],
         [15.]]]), array([], shape=(2, 2, 0), dtype=float64)]

### numpy.hsplit 
#### numpy.hsplit(ary ,indices_or_sections)

* Dividir una matriz en múltiples subarreglos horizontalmente (columna-sabio).

* hsplites equivale a split con axis=1, la matriz siempre se divide a lo largo del segundo eje independientemente de la dimensión de la matriz.

In [48]:
x = np.arange(16).reshape(4,4) ; x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
np.hsplit(x, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [50]:
np.hsplit(x, np.array((3,6)))

[array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14]]), array([[ 3],
        [ 7],
        [11],
        [15]]), array([], shape=(4, 0), dtype=int64)]

In [54]:
x = np.arange(24).reshape(4,6) ; x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [55]:
np.hsplit(x, np.array((3,6)))

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]]), array([], shape=(4, 0), dtype=int64)]

In [57]:
x = np.arange(8).reshape(2,2,2) ; x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [58]:
np.hsplit(x, 2)

[array([[[0, 1]],
 
        [[4, 5]]]), array([[[2, 3]],
 
        [[6, 7]]])]

### numpy.vsplit 
#### numpy.vsplit( ary , indices_or_sections ) [fuente]

* Dividir una matriz en múltiples subarreglas verticalmente (en forma de fila).

* vsplit es equivalente a split con eje = 0 (predeterminado), la matriz siempre se divide a lo largo del primer eje independientemente de la dimensión de la matriz.

In [69]:
x = np.arange(16).reshape(4,4) ; x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [78]:
np.vsplit(x, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [73]:
np.vsplit(x, np.array((3,6)))

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([], shape=(0, 4), dtype=int64)]

In [76]:
y = np.arange(8).reshape(2,2,2) ; y

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [77]:
np.vsplit(y, 2)

[array([[[0, 1],
         [2, 3]]]), array([[[4, 5],
         [6, 7]]])]