In [1]:
import numpy as np

### numpy.tile 
#### numpy.tile(A ,reps)

* Construye una matriz repitiendo A la cantidad de veces que dan los representantes.

* Si las repeticiones tienen longitud d, el resultado tendrá dimensión de .max(d, A.ndim)

* Si , A se promueve a ser d-dimensional al anteponer nuevos ejes. Por lo tanto, una matriz shape (3) se promueve a (1, 3) para la replicación 2-D, o forma (1, 1, 3) para la replicación 3-D. Si este no es el comportamiento deseado, promueva A a d-dimensiones manualmente antes de llamar a esta función.A.ndim < d

* Si , las repeticiones se promueven a A .ndim por 1s pre-pendientes. Así, para una A de forma (2, 3, 4, 5), una repetición de (2, 2) se trata como (1, 1, 2, 2).A.ndim > d

* Nota: Aunque los mosaicos pueden usarse para la transmisión, se recomienda encarecidamente usar las operaciones y funciones de transmisión de numpy.

In [5]:
a = np.array((0,1,2)) ; a

array([0, 1, 2])

In [6]:
np.tile(a,2)

array([0, 1, 2, 0, 1, 2])

In [10]:
np.tile(a, (2,2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [11]:
np.tile(a, (2,2,2))

array([[[0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2]],

       [[0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2]]])

In [12]:
b = np.array(((1,2),(3,4))) ; b

array([[1, 2],
       [3, 4]])

In [13]:
np.tile(b, 2)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [17]:
np.tile(b, (2,1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [18]:
c = np.array((1,2,3,4)) ; c

array([1, 2, 3, 4])

In [19]:
np.tile(c, (4,1))

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

### numpy.repeat 
#### numpy.repeat( a , repeticiones , eje = Ninguno ) [fuente]
* Repetir elementos de una matriz.

In [20]:
np.repeat(3,4)

array([3, 3, 3, 3])

In [21]:
x = np.array(((1,2), (3,4))) ; x

array([[1, 2],
       [3, 4]])

In [25]:
np.repeat(x, 3, axis=0)

array([[1, 2],
       [1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4]])

In [43]:
np.repeat(x, 3, axis=1)

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

---

In [42]:
np.repeat(x, [1,3], axis=0)

array([[1, 2],
       [3, 4],
       [3, 4],
       [3, 4]])

In [44]:
np.repeat(x, [1,3], axis=1)

array([[1, 2, 2, 2],
       [3, 4, 4, 4]])

---

In [35]:
np.repeat(x, [3,1], axis=0)

array([[1, 2],
       [1, 2],
       [1, 2],
       [3, 4]])

In [36]:
np.repeat(x, [3,1], axis=1)

array([[1, 1, 1, 2],
       [3, 3, 3, 4]])