In [1]:
import numpy as np

### numpy.flip 
#### numpy.flip (m, eje=Ninguno)
- Invierte el orden de los elementos en una matriz a lo largo del eje dado.
---



In [8]:
a = np.arange(8).reshape(2,2,2)

In [9]:
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
np.flip(a)

array([[[7, 6],
        [5, 4]],

       [[3, 2],
        [1, 0]]])

In [16]:
np.flip(a, 0)

array([[[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])

In [17]:
np.flip(a, 1)

array([[[2, 3],
        [0, 1]],

       [[6, 7],
        [4, 5]]])

In [18]:
np.flip(a, 2)

array([[[1, 0],
        [3, 2]],

       [[5, 4],
        [7, 6]]])

In [19]:
a = np.random.randn(3,4,5) ;a

array([[[ 0.59254513,  1.36684447,  0.63917882,  0.62226471,
          0.64679134],
        [ 0.57417266, -1.52448624, -1.22314158, -0.76685537,
         -0.9993356 ],
        [ 0.10793128,  0.03055699, -0.03968486,  1.15715667,
         -0.06844097],
        [-1.05613555, -1.12111541,  0.5823431 , -0.15190479,
          0.02346434]],

       [[ 0.54065483,  0.39327036, -0.95829578,  0.23608669,
         -0.97060384],
        [ 1.43426762, -0.54511038,  0.50598111, -0.97441728,
          1.75526081],
        [-0.34860286, -0.41142169, -0.01357141,  0.08070104,
         -0.25473546],
        [-1.18194307,  0.46806436, -1.2684117 , -0.82155398,
          0.1662783 ]],

       [[-0.80848414,  0.45879032,  0.71792247,  0.32072921,
          2.66510879],
        [-1.11710992,  0.06507456, -1.55077827,  0.42381335,
         -0.46817843],
        [-1.13894385, -0.04903112, -2.2072851 ,  0.23745092,
         -0.59134608],
        [-1.18760049,  0.78434162,  1.60593729,  0.67427702,
          0

In [25]:
np.all(np.flip(a, 2) == a[:,:,::-1,...])

True

---
### numpy.fliplr 
#### numpy.fliplr(m)

- Voltea la matriz en la dirección izquierda / derecha.

- Voltear las entradas en cada fila en la dirección izquierda/derecha. Las columnas se conservan, pero aparecen en un orden diferente al anterior.
---

In [28]:
a = np.diag((1,2,3,4))

In [29]:
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [30]:
np.fliplr(a)

array([[0, 0, 0, 1],
       [0, 0, 2, 0],
       [0, 3, 0, 0],
       [4, 0, 0, 0]])

---

In [37]:
a = np.random.randn(2,3,5)

In [38]:
a

array([[[-0.01377623,  0.20665365,  1.6330294 , -0.59389439,
         -1.46439492],
        [ 0.19311775, -0.71533988,  0.38615136, -0.18542829,
          1.36072959],
        [-0.35690997, -0.46791372, -0.8786741 , -0.18223786,
         -0.89258061]],

       [[-0.7453612 ,  0.49956953,  1.02172173, -1.0817049 ,
          0.86448674],
        [-0.57889364, -1.00089278, -0.98861255, -0.62302341,
          0.5086579 ],
        [ 1.32996683,  0.47121797,  0.6445272 , -0.55468582,
          1.78151464]]])

In [41]:
np.all(np.fliplr(a) == a[:,::-1,...])

True

---
### numpy.flipud 
##### numpy.flipud(m)
* Voltear matriz en la dirección arriba / abajo.

* Voltear las entradas en cada columna en la dirección arriba / abajo. Las filas se conservan, pero aparecen en un orden diferente al anterior.
---

In [43]:
a = np.diag((1.,2,3))
a

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [44]:
np.flipud(a) # Hace efecto mirror en axis=1

array([[0., 0., 3.],
       [0., 2., 0.],
       [1., 0., 0.]])

In [45]:
np.fliplr(a) # Hace efecto mirror en axis=0

array([[0., 0., 1.],
       [0., 2., 0.],
       [3., 0., 0.]])

---

In [47]:
a = np.random.randn(2,3,5)


In [48]:
np.all(np.flipud(a) == a[::-1])

True

---

In [49]:
np.flipud((1,2))

array([2, 1])

---
### numpy.reshape 
##### numpy.reshape(a, newshape, order='C')
* Da una nueva forma a una matriz sin cambiar sus datos.
---

In [55]:
a = np.zeros((10,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [56]:
b= a.T
b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [57]:
c = b.view()
c

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [59]:
c.shape = (20) ### Error forzado

AttributeError: incompatible shape for a non-contiguous array

---

In [60]:
a = np.arange(6).reshape((3,2))

In [61]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

---

In [62]:
np.reshape(a, (2,3))

array([[0, 1, 2],
       [3, 4, 5]])

In [63]:
np.reshape(np.ravel(a), (2,3))

array([[0, 1, 2],
       [3, 4, 5]])

In [64]:
np.reshape(a, (2,3), order="F")

array([[0, 4, 3],
       [2, 1, 5]])

In [65]:
np.reshape(np.ravel(a, order="F"), (2,3), order="F")

array([[0, 4, 3],
       [2, 1, 5]])

---

In [68]:
a = np.array(((1,2,3), (4,5,6))) ; a

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
np.reshape(a, 6, order="F")

array([1, 4, 2, 5, 3, 6])

---

In [70]:
np.reshape(a, (3,-1))

array([[1, 2],
       [3, 4],
       [5, 6]])

---
### numpy.roll 
#### numpy.roll(a, shift, axis=None)

* Desplaza los elementos de una matriz a lo largo de un eje dado.
* Los elementos que ruedan más allá de la última posición se reintroducen en la primera.
---

In [71]:
x = np.arange(10)

In [72]:
np.roll(x, 2)

array([8, 9, 0, 1, 2, 3, 4, 5, 6, 7])

---

In [73]:
x2 = np.reshape(x, (2,5))

In [74]:
x2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [75]:
np.roll(x2, 1)

array([[9, 0, 1, 2, 3],
       [4, 5, 6, 7, 8]])

In [76]:
np.roll(x2, 1, axis=0)

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [77]:
np.roll(x2, 1, axis=1)

array([[4, 0, 1, 2, 3],
       [9, 5, 6, 7, 8]])

---
### numpy.rot90 
#### numpy.rot90(m, k=1, ejes=(0,1))

* Gira una matriz 90 grados en el plano especificado por los ejes.

* La dirección de rotación es desde el primero hacia el segundo eje.
---

In [78]:
m = np.array(((1,2), (3,4)), int)

In [79]:
m

array([[1, 2],
       [3, 4]])

In [80]:
np.rot90(m)

array([[2, 4],
       [1, 3]])

In [83]:
np.rot90(m, 2)

array([[4, 3],
       [2, 1]])

In [84]:
np.rot90(m, 3)

array([[3, 1],
       [4, 2]])

In [85]:
m = np.arange(8).reshape((2,2,2))

In [86]:
m

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [92]:
np.rot90(m, 1, (1,2))

array([[[1, 3],
        [0, 2]],

       [[5, 7],
        [4, 6]]])