In [1]:
import numpy as np

In [2]:
print (np.__version__)

1.15.4


In [3]:
np.show_config()

mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/camilopinochet/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/camilopinochet/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/camilopinochet/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/camilopinochet/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/camilopinochet/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/camilopinochet/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/camilopinochet/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/camilopinochet/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_

In [4]:
z = np.zeros(10)

In [5]:
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
z = np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
z=np.arange(10,50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [8]:
z=np.arange(50)
z=z[::-1]
z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [9]:
x = np.arange(0,9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
x = np.nonzero([1,2,0,1,5,0,0,9])
x

(array([0, 1, 3, 4, 7]),)

In [11]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
y = np.random.randn(3,3,3)

In [13]:
y = np.random.randn(10,10)
np.min(y), y.min(), np.max(y), y.max()


(-2.4644485595146848,
 -2.4644485595146848,
 2.0836508433878014,
 2.0836508433878014)

In [14]:
y = np.arange(30)
y.mean()

14.5

In [15]:
x = np.ones((3,3))
x[1:-1, 1:-1]=1
x[1,1]

1.0

In [16]:
z = np.ones((10,10))
z[1:-1, 1:-1]=7
z[1:1, 1:1]=0
z[1,1]

7.0

In [17]:
np.nan == np.nan

False

In [18]:
np.inf>np.nan

False

In [19]:
np.nan-np.nan

nan

In [20]:
i = np.arange(25).reshape(5,5);i


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

In [27]:
x=np.arange(336).reshape(6,7,8)
x

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55]],

       [[ 56,  57,  58,  59,  60,  61,  62,  63],
        [ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111]],

       [[112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127],
        [128, 129, 130, 131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147, 148, 149, 150, 151],
        [152, 153, 154, 155, 156, 157, 158, 15