In [18]:
import numpy as np

---
#### numpy.fv (rate, nper, pmt, pv, when='end')
* Calcular el valor futuro.

In [2]:
np.fv(0.05/12, 10*12, -100, -100)

15692.928894335748

In [3]:
a = np.array((0.05, 0.06, 0.07))/12

In [4]:
np.fv(a, 10*12, -100, -100)

array([15692.92889434, 16569.87435405, 17509.44688102])

---
#### numpy.pv (rate, nper, pmt, fv=0, when='end')
* Calcular el valor presente.

In [6]:
np.pv(0.05/12, 10*12, -100, 15692.93)

-100.00067131625819

In [7]:
a = np.array((0.05, 0.04, 0.03))/12

In [10]:
np.pv(a, 10*12, -100, 15692.93)

array([ -100.00067132,  -649.26771385, -1273.78633713])

---
#### numpy.npv (tasa, valores)
* Devuelve el NPV (valor actual neto) de una serie de flujo de efectivo.

In [11]:
np.npv(0.281, [-100, 39, 59, 55, 20])

-0.00847859163845488

---
#### numpy.pmt (rate, nper, pv, fv=0, when='end')
* Calcular el pago contra el principal del préstamo más los intereses.

In [14]:
np.pmt(0.075/12, 12*15, 200000)

-1854.0247200054619

---
#### numpy.ppmt ( rate , per , nper , pv , fv = 0 , when = 'end' )
* Calcular el pago contra el principal del préstamo.

----
#### numpy.ipmt( rate , per , nper , pv , fv = 0 , when = 'end' )
* Calcule la parte de interés de un pago.

In [15]:
principal = 2500.00

In [26]:
per = np.arange(1*12)+1

In [27]:
ipmt = np.ipmt(0.0824/12, per, 1*12, principal)

In [28]:
ppmt = np.ppmt(0.0824/12, per, 1*12, principal)

In [29]:
pmt = np.pmt(0.0824/12, 1*12, principal)

In [32]:
np.allclose(ipmt + ppmt, pmt)

True

In [33]:
fmt = '{0:2d} {1:8.2f} {2:8.2f} {3:8.2f}'

In [35]:
for payment in per:
    index = payment - 1
    principal = principal + ppmt[index]
    print(fmt.format(payment, ppmt[index], ipmt[index], principal))

 1  -200.58   -17.17  2299.42
 2  -201.96   -15.79  2097.46
 3  -203.35   -14.40  1894.11
 4  -204.74   -13.01  1689.37
 5  -206.15   -11.60  1483.22
 6  -207.56   -10.18  1275.66
 7  -208.99    -8.76  1066.67
 8  -210.42    -7.32   856.25
 9  -211.87    -5.88   644.38
10  -213.32    -4.42   431.05
11  -214.79    -2.96   216.26
12  -216.26    -1.49    -0.00


In [36]:
intersestpd = np.sum(ipmt) 

In [37]:
np.round(intersestpd, 2)

-112.98

---
#### numpy.irr( valores ) [fuente]
* Devuelva la tasa interna de retorno (TIR).
https://docs.scipy.org/doc/numpy/reference/generated/numpy.irr.html#numpy.irr

In [39]:
round(np.irr([-100, 39, 59, 55, 20]), 5)

0.28095

In [40]:
round(np.irr([-100, 0, 0, 74]), 5)

-0.0955

In [41]:
round(np.irr([-100, 100, 0, -7]), 5)

-0.0833

In [42]:
round(np.irr([-100, 100, 0, 7]), 5)

0.06206

In [43]:
round(np.irr([-5, 10.5, 1, -8, 1]), 5)

0.0886

---
#### numpy.mirr( valores , finance_rate , reinvest_rate )
* Modificación de la tasa interna de retorno.

---
#### numpy.nper( rate , pmt , pv , fv = 0 , when = 'end' )
* Calcule el número de pagos periódicos.

In [47]:
np.nper(0.07/12, -150, 8000)

array(64.07334877)

In [48]:
np.nper(*(np.ogrid[0.07/12: 0.08/12: 0.01/12,
                  -150 : -99:  50  ,
                  8000:  9001:   1000]))

array([[[ 64.07334877,  74.06368256],
        [108.07548412, 127.99022654]],

       [[ 66.12443902,  76.87897353],
        [114.70165583, 137.90124779]]])

---
#### numpy.rate(nper, pmt, pv, fv, when='end', guess=None, tol=None, maxiter=100)
* Calcula la tasa de interés por periodo.